### ISSUE TITLE
TODO tripal

### ISSUE THREAD

**Issue by abretaud** [galaxy-genome-annotation/dockerized-gmod-deployment#4]
Some things to be done for tripal:
- [ ] [python-tripal](https://github.com/abretaud/python-tripal): Python scripts to load specific data using REST API/python-tripal
  - [x] fasta (a generic script would be better, but easy to implement with rest)
  - [x] gff (this one too)
  - [x] sync features
  - [x] blast results (tripal_analysis_blast)
    - [x] add some tripal-specific analysis properties in analysisprop table https://github.com/tripal/tripal_analysis_blast/blob/7.x-2.x/includes/tripal_analysis_blast.chado_node.inc#L390
  - [x] interpro results (tripal_analysis_blast)
    - [x] add some tripal-specific analysis properties in analysisprop table https://github.com/tripal/tripal_analysis_interpro/blob/7.x-2.x/includes/tripal_analysis_interpro.chado_node.inc#L262
  - [x] go annotation (https://github.com/tripal/tripal_analysis_go/, seems to be dead)
  - [ ] expression data (https://github.com/tripal/tripal_analysis_expression)
  - [ ] more? kegg?
- [ ] [python-chado](https://github.com/abretaud/python-chado)
  - [x] create organism
  - [x] create analysis
  - [ ] tools from https://github.com/TAMU-CPT/CHAPLIN?
- [x] Galaxy tools
  - [x] python-chado tools
  - [x] python-tripal tools
  - [x] Auth from galaxy in the same way as apollo (=store somewhere the url + login/pass and use it in each tool)
- [x] use https://www.drupal.org/project/tripal_daemon to launch jobs instead of cron? requires php compiled with pcntl support...
- [x] indexing/search
  - [x] using elasticsearch
- [x] ENV to configure tripal theme
- [x] update to tripal 2.1 erasche/docker-tripal#9 erasche/docker-tripal#6

**Comment by abretaud** [comment]
@erasche don't hesitate to complete/change this list!

I don't remember where the apollo galaxy wrappers are, should we have a repo for that or use an existing one (IUC even if they will be quite exotic tools?)

Also, I have a bunch of PR waiting on tripal's gihub repos, I hope they will be merges soon

**Comment by hexylena** [comment]
@abretaud absolutely :)

Currently they are here https://github.com/TAMU-CPT/galaxy-apollo, but I intend to move them into IUC once we get this user KV store implemented with @bgruening and K. Beaulieu and can implement the idea of tools declaring that they need username/passwords for remote services.

**Comment by bgruening** [comment]
I made some good progress and the user-preferences, I hope I will have something next week, or the week after.

**Comment by abretaud** [comment]
@bgruening excellent! looking forward to test it!

**Comment by abretaud** [comment]
@erasche in the wrappers you wrote for chado, do you already have ones to create organisms and analysis?

**Comment by hexylena** [comment]
@abretaud doesn't look like it https://github.com/TAMU-CPT/CHAPLIN

(my prof gave me an order that I was to choose memorable and "cute" names. Apparently he didn't actually expect me to follow through with it, but I did, so everything that we produced for a couple years had some really awful acronyms...)

**Comment by abretaud** [comment]
Beautiful (and memorable) name!
I can write something for this, but I had a perl overdose in the past... Any objection to a new python-chado lib (the name is unused!)?

**Comment by hexylena** [comment]
Absolutely no objection at all, I would very much enjoy ridding myself of all the old perl code we used to use. (If you would want,) we could simply replace the current CHAPLIN with python versions of the actual scripts, if you're working on a python-chado library.

**Comment by abretaud** [comment]
All right, let's celebrate the birth of python-chado! : https://github.com/abretaud/python-chado
(Completely untested, I just copy-pasted some code I found on my HDD to my own surprise)
I'll see if it can replace CHAPLIN completely or not (btw, are you aware there are some db password in it?)

**Comment by hexylena** [comment]
Wonderful :)

(And yes, there are some db passwords, but those databases are no longer in existence so I did not bother removing them. Thanks for letting me know though!)

**Comment by hexylena** [comment]
Also should add https://github.com/isubit/tripal_jbrowse_api/ once we get licensing discussions resolved.

**Comment by abretaud** [comment]
Hej,
Now that I've progressed on the tripal front, I'm thinking about writing the galaxy tools for python-chado and python-tripal. Did you make progress on the user preferences KV store?
No hurry though, I have many other things on my todo list!

btw @erasche, I don't know if you've seen the latest changes in python-chado, it now uses better looking subcommands, I just hope it won't break too badly some of your scripts...

Anthony

**Comment by hexylena** [comment]
Hei @abretaud!

I have not, Katherine and @bgruening have been working on separate portions of that, not sure how far they've progressed.

I hadn't seen those, that looks awesome! Much cleaner, thank you :)
